version: 2

models:
  - name: dim_customer
    columns:
      - name: customer_key
        tests: [unique, not_null]
  - name: dim_product
    columns:
      - name: product_key
        tests: [unique, not_null]
  - name: dim_seller
    columns:
      - name: seller_key
        tests: [unique, not_null]
  - name: dim_date
    columns:
      - name: date_key
        tests: [unique, not_null]
  - name: fact_orders
    columns:
      - name: order_item_key
        tests: [unique, not_null]
      - name: customer_key
        tests:
          - not_null
          - relationships:
              to: ref('dim_customer')
              field: customer_key
      - name: product_key
        tests:
          - relationships:
              to: ref('dim_product')
              field: product_key
      - name: seller_key
        tests:
          - relationships:
              to: ref('dim_seller')
              field: seller_key
      - name: order_status
        tests:
          - accepted_values:
              values: [created, approved, invoiced, processing, shipped, delivered, unavailable, canceled]
  - name: fact_payments
    columns:
      - name: payment_key
        tests: [unique, not_null]
